export const RECEIVED_DATA = "RECEIVED_DATA";

export const AUTH_START = "AUTH_START ";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const SAVE_POST_SUCCESS = "SAVE_POST_SUCCESS";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
